use_frameworks!

platform :ios, '9.0'

target 'FTYBaseView_Example' do
  pod 'FTYBaseView', :path => '../'

  target 'FTYBaseView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
